# Generated by Django 6.0.7 on 2026-07-18 22:00

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('canonical_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawRateResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('payload', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('source', models.CharField(max_length=20)),
                ('source_url', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('parsed', 'Parsed'), ('rejected', 'Rejected')], max_length=10)),
                ('error', models.TextField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='raw_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_type', models.CharField(choices=[('15yr_fixed_mortgage', '15yr_fixed_mortgage'), ('30yr_fixed_mortgage', '30yr_fixed_mortgage'), ('5yr_arm_mortgage', '5yr_arm_mortgage'), ('savings_1yr_fixed', 'savings_1yr_fixed'), ('savings_easy_access', 'savings_easy_access')], max_length=50)),
                ('rate_value', models.DecimalField(decimal_places=4, max_digits=6)),
                ('currency', models.CharField(max_length=3)),
                ('effective_date', models.DateField()),
                ('observed_at', models.DateTimeField()),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rates', to='rates.provider')),
                ('raw_response', models.OneToOneField(db_column='raw_response_id', on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='rates.rawrateresponse', to_field='response_id')),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'rate_type', '-effective_date', '-observed_at'], name='rate_latest_idx'), models.Index(fields=['rate_type', '-effective_date'], name='rate_type_date_idx'), models.Index(fields=['ingested_at'], name='rate_ingested_idx')],
            },
        ),
    ]
